import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {renderDocument} from '../idea-zone/skills/share-idea/assets/render.mjs';
const basic={title:'My idea',pages:[{title:'Overview',markdown:'Hello **reader**.'}]};
test('renders content in each layout and palette without bundling a layout switcher',()=>{for(const style of ['brief','editorial','report'])for(const palette of ['neutral','warm','sage','midnight']){const html=renderDocument({...basic,style,palette,pages:[...basic.pages,{title:'Plan',markdown:'| Step | Owner |\n| --- | --- |\n| Try | Us |\n\n> A quote\n\n```js\nlet x = 1;\n```'}]});assert.match(html,/<strong>reader<\/strong>/);assert.match(html,/<table>/);assert.match(html,/<blockquote>/);assert.match(html,/<pre><code/);assert.match(html,/<section class="document-section" id="page-2"/);assert.match(html,new RegExp('data-style="'+style+'"'));assert.match(html,new RegExp('data-palette="'+palette+'"'));assert.match(html,/data-palette-choice="midnight"/);assert.match(html,/data-font-choice="serif"/);assert.match(html,/font-src data:/);assert.match(html,/@font-face/);assert.doesNotMatch(html,/<select[^>]+id="style"|Made with Idea Zone|An idea worth sharing|<script[^>]+src=|<link[^>]+href=/);if(style==='report')assert.match(html,/<span class="section-number">02<\/span>/);else assert.doesNotMatch(html,/<span class="section-number">/);}});
test('preserves legacy input as an initial palette and defaults to Brief and Neutral',()=>{const html=renderDocument(basic);assert.match(html,/data-style="brief" data-palette="neutral"/);for(const [theme,palette]of Object.entries({sage:'sage',paper:'warm',midnight:'midnight'}))assert.match(renderDocument({...basic,theme}),new RegExp('data-palette="'+palette+'"'))});
test('embeds local raster images and fails clearly for missing or remote assets',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'idea-zone-'));try{fs.writeFileSync(path.join(dir,'image.png'),Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aBVkAAAAASUVORK5CYII=','base64'));const doc={...basic,pages:[{title:'Image',markdown:'![A dot](./image.png)'}]};const html=renderDocument(doc,dir);assert.match(html,/src="data:image\/png;base64,/);assert.match(html,/alt="A dot"/);assert.throws(()=>renderDocument({...basic,pages:[{title:'Bad',markdown:'![Missing](./missing.png)'}]},dir),/ENOENT/);assert.throws(()=>renderDocument({...basic,pages:[{title:'Bad',markdown:'![Remote](https:\/\/example.com\/image.png)'}]}),/Images must be local/)}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('treats conversation HTML as text and removes executable links',()=>{const html=renderDocument({title:'<script>bad()</script>',pages:[{title:'<img src=x onerror=bad()>',markdown:'<script>alert(1)</script>\n\n[bad](javascript:alert%281%29)\n\n[good](https://example.com)'}]});assert.doesNotMatch(html,/<script>alert\(1\)<\/script>|href="javascript:|<img src=x/);assert.match(html,/&lt;script&gt;/);assert.match(html,/href="https:\/\/example.com"/)});
test('rejects invalid input instead of making a broken document',()=>{for(const doc of [{},{title:'x',pages:[]},{...basic,theme:'unknown'},{...basic,style:'unknown'},{...basic,palette:'unknown'},{...basic,font:'unknown'},{...basic,pages:[{title:'x'}]}])assert.throws(()=>renderDocument(doc))});
test('bundled CLI runs in isolation without node_modules',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'idea-zone-cli-'));try{fs.copyFileSync('idea-zone/skills/share-idea/assets/render.mjs',dir+'/render.mjs');fs.writeFileSync(dir+'/idea.json',JSON.stringify(basic));execFileSync(process.execPath,[dir+'/render.mjs',dir+'/idea.json',dir+'/idea.html']);assert.match(fs.readFileSync(dir+'/idea.html','utf8'),/<strong>reader<\/strong>/)}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('landing page is one file with working embedded download payloads',()=>{const html=fs.readFileSync('dist/index.html','utf8');assert.doesNotMatch(html,/__[A-Z_]+__|<script[^>]+src=|<link[^>]+rel="stylesheet"/);const packed=html.match(/id="download-plugin"[^>]+href="data:application\/zip;base64,([A-Za-z0-9+/=]+)"/);assert.ok(packed);assert.equal(Buffer.from(packed[1],'base64').subarray(0,2).toString(),'PK');const docs=JSON.parse(html.match(/<script type="application\/json" id="example-data">(.*?)<\/script>/s)[1]);assert.equal(Object.keys(docs).length,3);for(const style of ['brief','editorial','report'])assert.match(docs[style],new RegExp('data-style="'+style+'"'))});

test('supports meaningful Markdown: captions, tasks, nested lists, callouts, code and page-local footnotes',()=>{const html=renderDocument({...basic,pages:[{title:'First',markdown:'- [x] Done\n- [ ] To do\n\n1. Step\n   - Detail\n\n~~Discarded~~ and *aside*.\n\n> [!WARNING]\n> Keep the previous release.\n\n```json\n{"name":"project"}\n```\n\nSource[^a].\n\n[^a]: [Details](https://example.com)'},{title:'Second',markdown:'Other source[^a].\n\n[^a]: A different note.'}]});assert.match(html,/checked/);assert.match(html,/<del>Discarded<\/del>/);assert.match(html,/class="callout callout-warning"/);assert.match(html,/hljs-attr/);assert.match(html,/page-1-note-a/);assert.match(html,/page-2-note-a/);assert.doesNotMatch(html,/href="javascript:/)});
test('illustrated examples actually cover images and Markdown features and include captions',()=>{const brief=fs.readFileSync('examples/brief.html','utf8'),editorial=fs.readFileSync('examples/editorial.html','utf8'),report=fs.readFileSync('examples/report.html','utf8');for(const html of [brief,editorial,report]){assert.match(html,/<figure[^>]*><img src="data:image\/webp;base64,/);assert.match(html,/<figcaption>/);assert.match(html,/<table>/);assert.match(html,/type="checkbox"/);assert.doesNotMatch(html,/<img[^>]+src="https?:/)}assert.match(editorial,/class="footnotes"/);assert.match(report,/hljs-keyword/)});
